### ISSUE TITLE
Copy strings without quotes

### ISSUE THREAD

**Issue by marcklingen** [YYsuni/react18-json-view#16]
The users of my project often copy individual string values from the json rendered with react18-json-view (I got great feedback on the new json view by the way 🙏). I'd like to customize the copy behavior of strings to not include double quotes.

Is this a better default copy behavior for everyone (changing the default) or what are your thoughts on supporting custom `stringifyForCopying` functions?

---
![Screenshot 2023-09-26 at 15 02 41](https://github.com/YYsuni/react18-json-view/assets/2834609/c98c5f3a-3aeb-4379-977c-35ad08af5490)

**Comment by marcklingen** [comment]
(I'd be happy to contribute the change if you agree that it is a better default)

**Comment by YYsuni** [comment]
You make a valid point. The default behavior for copying strings should be to remove the quotation marks, and it would also be beneficial to provide users with a customization option.
