### ISSUE TITLE
what happened? What picture is this?

### ISSUE THREAD

**Issue by YuZongYangHi** [YYsuni/react18-json-view#20]
<img width="680" alt="image" src="https://github.com/YYsuni/react18-json-view/assets/35584408/9f2ba0ab-62ef-4f33-81c3-d9c677150240">

**Comment by YuZongYangHi** [comment]
<img width="931" alt="image" src="https://github.com/YYsuni/react18-json-view/assets/35584408/8f3f27a9-0003-4169-aa67-ea8ebd998f8a">

**Comment by YuZongYangHi** [comment]
```
import JsonView from 'react18-json-view'
import 'react18-json-view/src/style.css'

<JsonView collapseStringsAfterLength={100000} 
    src={jsonData} 
    collapsed={false}  
    theme="default" />
```

**Comment by YuZongYangHi** [comment]
The style of your project will be lost. My project is umijs4 + antd pro.

**Comment by YuZongYangHi** [comment]
@YYsuni

**Comment by YuZongYangHi** [comment]
The first time I used it, it was really terrible...

**Comment by YYsuni** [comment]
Hmmm... Let me see....🧐

**Comment by YYsuni** [comment]
Don't worry, could you show a demo code? Like CodeSandbox or an online website.
@YuZongYangHi

**Comment by YuZongYangHi** [comment]
@YYsuni  I solved it with react-json-view, but I don’t know why the style is missing in your project. The expanded and collapsed icons are abnormally large.

**Comment by YYsuni** [comment]
ok, I will continue to further research.

**Comment by YuZongYangHi** [comment]
There is a high probability that it is a problem with my json

**Comment by felixSchl** [comment]
I am running into the same problem. Have you solved this?

**Comment by 7inug1** [comment]
@felixSchl add the style imports to the top and it was gone for me

**Comment by felixSchl** [comment]
Thanks, that worked. I misread the docs as replacing the styles import for
dark styles as opposed to adding another import.

**Comment by freds-dev** [comment]
I am having the same problem within my Remix app. None of the fixes here helped solving it. Any other ideas?

```
import JsonView from 'react18-json-view'
import 'react18-json-view/src/style.css'

const jsonObject = {
  string: "string",
  number: 123456,
  boolean: false,
  null: null,
  func: "function(){}",
  Symbol: "Symbol(JSON View)",
  obj: { k1: 123, k2: "123", k3: false },
  arr: ["string", 123456, false, null],
};

export default function MqttOptions() {
  return <JsonView src={jsonObject} />;
}
```

**Comment by YYsuni** [comment]
> I am having the same problem within my Remix app. None of the fixes here helped solving it. Any other ideas?
@freds-dev 
The latest canary version may resolve the problem, please use v0.2.8-canary.6 by `npm i react18-json-view@canary`.
