### ISSUE TITLE
Dark Mode does not seem to work?

### ISSUE THREAD

**Issue by Rietty** [YYsuni/react18-json-view#3]
Hi, I downloaded the latest version 0.2.1 and followed the guide of importing and then setting up the Dark Mode, however it fails to swap the view over/stays light colours. Is there anything else?

I import following:

```
import JsonView from 'react18-json-view'
import 'react18-json-view/src/style.css'
import 'react18-json-view/src/dark.css'
```

And use as such:
```
<div class="item rightpane">
<JsonView src={myFormData} collapsed={false} dark={true} />
</div>
```

Also wanted to say thank you so much for making this, it works fantastic and is a great help to me!

**Comment by YYsuni** [comment]
The dark property just helps you keep component in dark mode. To make it flexible, you only need to import the dark.css file. Then, you can set the dark class on any parent component (such as html).

You can visit the website https://jv.yysuni.com/ and learn about how it works by examining this [file](https://github.com/YYsuni/json-view-online/blob/main/src/components/theme.tsx).

**Comment by YYsuni** [comment]
Don't forget to give me a star if it's helpful for you~~ 🥰😁

**Comment by Rietty** [comment]
> The dark property just helps you keep component in dark mode. To make it flexible, you only need to import the dark.css file. Then, you can set the dark class on any parent component (such as html).
> 
> You can visit the website https://jv.yysuni.com/ and learn about how it works by examining this [file](https://github.com/YYsuni/json-view-online/blob/main/src/components/theme.tsx).

So if I understand it, I need to set a dark-mode on my overall website/app for it to reflect in the JSON View?

**Comment by YYsuni** [comment]
Yes..

**Comment by Rietty** [comment]
Got it, thank you! (I did star project by the way!) <3
