### ISSUE TITLE
Do not collapse string when selecting parts of it

### ISSUE THREAD

**Issue by marcklingen** [YYsuni/react18-json-view#33]
A user of our project reported this bug/idea and I thought that this could be a nice improvement for other users of react18-json-view as well: https://github.com/langfuse/langfuse/issues/1189

Recording of issue
![Untitled video - Made with Clipchamp](https://github.com/langfuse/langfuse/assets/7263579/c2e578ca-a3a5-4fb2-8c9b-ee774a86bdae)

Suggestion: when a string is expanded and user selects parts of it, prevent collapse

@YYsuni what do you think about this? Is this something that's a general improvement of this project or rather implemented by us as an override for the string node?

**Comment by YYsuni** [comment]
Wow..., It's actually a terrible experience. I will fix it today.

**Comment by YYsuni** [comment]
v0.2.8-canary.1 available now.

**Comment by YYsuni** [comment]
@marcklingen Hello?

**Comment by marcklingen** [comment]
Thanks for the ping, will try this asap

**Comment by marcklingen** [comment]
Works perfectly, thank you 🙏
