### ISSUE TITLE
`editable`: jump from key to value on `:`

### ISSUE THREAD

**Issue by marcklingen** [YYsuni/react18-json-view#37]
The editing of json in react18-json-view could work similarly as in the chrome dev tools where the editor automatically jumps from key to value when typing an `:`. What do you think? Are there use cases of including `:` in the key itself? This would make editing way easier.

Example
![CleanShot 2024-02-26 at 16 56 36](https://github.com/YYsuni/react18-json-view/assets/2834609/6c827f2f-eb5b-492a-8b5b-29e46891bf18)

**Comment by YYsuni** [comment]
It seems need much codes, ok 🫡

**Comment by marcklingen** [comment]
Hi @YYsuni, I got a lot of feedback by our users who edit a lot of JSON within our application. We switched to codemirror for editing and use react18-json-viewer for viewing of JSON across the UI. Thanks for you effort on this!
