### ISSUE TITLE
Custom Icons

### ISSUE THREAD

**Issue by BrianHung** [YYsuni/react18-json-view#44]
Library looks great! One question, is there a way to have custom icons / components for the copy, edit, or delete actions?

**Comment by YYsuni** [comment]
Owo, I will.

**Comment by YYsuni** [comment]
I have simply added custom copy/copied icon property at the latest canary version. Please check it.

**Comment by BrianHung** [comment]
Works well; might be a typo with "CopidComponent" instead of "CopiedComponent".

**Comment by kirillbashtenko** [comment]
@YYsuni Great Library!
Can we also add the same for other icons Edit, Confirm Edit, and Cancel Edit?
Thanks!

**Comment by YYsuni** [comment]
@kirillbashtenko ❤️ Lastest canary version released.

**Comment by BrianHung** [comment]
Closing as its available in canary; thanks!
