### ISSUE TITLE
feature request: support copy to clipboard when it's not https 

### ISSUE THREAD

**Issue by daolanfler** [YYsuni/react18-json-view#55]
First, thanks for the library. Currently copy only works with https as [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard) only works in secure context, is it possible to use something like [cope-to-clipboard](https://www.npmjs.com/package/copy-to-clipboard) , or at least let the user choose the copy method.

**Comment by YYsuni** [comment]
Ok, I will fix that.

**Comment by YYsuni** [comment]
@daolanfler I have add it on [v0.2.9-canary.8](https://www.npmjs.com/package/react18-json-view/v/0.2.9-canary.8) , you can check it now.
![image](https://github.com/user-attachments/assets/c532d581-85c1-4c04-af17-b9971630c6b7)
![image](https://github.com/user-attachments/assets/6da12ab9-4416-4697-881c-77f69e025ce5)

**Comment by daolanfler** [comment]
@YYsuni  I see, thanks!
